version: "3.2"
services:
  api:
    container_name: api  
    image: node:14
    restart: always
    working_dir: /usr/src/api
    command: bash -c "npm install && npm run build && npm start"
    environment:
      - DATABASE_URL=$DATABASE_URL
    volumes:
      - ./:/usr/src/api/:z
    ports:
      - "3010:3010"
