version: "3.2"
services:
  nodejs:
    container_name: api  
    image: node:14
    restart: always
    working_dir: /usr/src/api
    command: bash -c "npm install && npm run build && npm start"
    environment:
      - MONGO_URL=$MONGO_URL 
      - PIPEDRIVE_TOKEN=$PIPEDRIVE_TOKEN  
      - BLING_TOKEN=$BLING_TOKEN  
    volumes:
      - ./:/usr/src/api/:z
    ports:
      - "3010:3010"
